"""Create deliberate date/filter edge cases using the supplied schema only."""
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
dump = (root / 'data/v1_schema_dump.sql').read_text()
tables = ['CSiM Hospitals and States', 'UTI Individual Current', 'UTI Individual Historical']
statements = ['-- Generated by scripts/generate_fixture.py; load only into the separate fixture database.', 'BEGIN;', 'CREATE SCHEMA v1;']
for name in tables:
    match = re.search(r'CREATE TABLE v1\."' + re.escape(name) + r'" \(.*?\n\);', dump, re.S)
    if not match:
        raise ValueError(f'Source schema is missing {name}')
    statements.append(match.group())
statements.append('INSERT INTO v1."CSiM Hospitals and States" VALUES (\'Demo State\',\'Hospital 91\',91),(\'Demo State\',\'Hospital 92\',92),(\'Empty State\',\'Hospital 93\',93);')
# Each tuple fixes the number of eligible culture-positive treated submissions
# and the subset without symptoms. Those small counts are independently usable
# in the test expectations; April also has a non-eligible denominator example.
periods = [
    (2025, 11, 91, 4, 2), (2025, 11, 92, 6, 1),
    (2025, 12, 91, 8, 2), (2025, 12, 92, 4, 3),
    (2026, 1, 91, 12, 9), (2026, 1, 92, 8, 2),
    (2026, 2, 92, 4, 2),
    (2026, 3, 91, 10, 0), (2026, 3, 92, 6, 3),
    (2026, 4, 92, 2, 1),
]
rows = []
for year, month, hospital, submitted, asymptomatic in periods:
    for index in range(submitted):
        rows.append((len(rows)+1, hospital, 3, int(index >= asymptomatic), month, year, 1, 1, 0, 1, 6 if hospital == 91 else 10, 2))
for index in range(5):
    rows.append((len(rows)+1, 91, 3, 1, 4, 2026, 0, 0, 1, 0, None, 2))
# A current record that is not complete must never contribute.
rows.append((len(rows)+1, 91, 3, 0, 3, 2026, 1, 1, 0, 1, 99, 0))
columns = 'record_id,hosp_name,location,sign_symp,month,year,ucx_positive,urinalysis,tx___1,tx___2,duration,qi_asb_complete'
values = ',\n'.join('('+','.join('NULL' if value is None else str(value) for value in row)+')' for row in rows)
statements.append(f'INSERT INTO v1."UTI Individual Current" ({columns}) VALUES\n{values};')
statements.append('COMMIT;')
(root / 'data/edge-cases.sql').write_text('\n\n'.join(statements)+'\n')
print(f'Generated {len(rows)} fixture records, including one excluded incomplete record.')
